### ISSUE TITLE
Marketing the Beta App

### ISSUE THREAD

**Issue by greenlinktransit** [codeforgreenville/trolley-tracker-ios-client#11]
The city's Information Department wanted to know if we were ready to market the Trolley Tracker beta app via the city's social media outlets.  We've already posted a short article on the Greenlink website (http://www.ridegreenlink.com/CivicAlerts.aspx?AID=392) and I saw that the Greenville News prepared a story, as well.

Anyway, given the spotty signals over the last few weekends I was wondering if you guys wanted to hold off on any additional marketing until we get to the root of the problem.  Let me know what you think.

**Comment by bikeoid** [comment]
I would ordinarily say "move forward", but based on the problem level over the weekend, I would say that it's not useful to publicize it at this time.

I would like to meet to explore ways of moving forward with the integrated tablet Internet solution (Wednesday?).

**Comment by greenlinktransit** [comment]
I'm free in the morning on Wednesday (until 11AM) but will be tied up after that.

**Comment by greenlinktransit** [comment]
And just a heads up....I mentioned the internet issues to our IT department and here's the response I received....

***************************
Those units aren't really tied to the craddle point. They are the same modems that are used for route match. 
Have the modems and tablets been rebooted? From my understanding, the tracker app will cache the data if the cell service is unavailable. Do you know if there is an update for the tracker app on the tablet? Is there a weekend support number for the app?
Mike Blizzard
Technical Services Manager | IT Department
City of Greenville, SC
864-467-5707

On Oct 31, 2015 9:14 PM, Grant Sparks <gsparks@greenvillesc.gov> wrote:
Hey Mike,

The Trolley Tracker app has been relaying spotty locations this weekend. Yesterday both trolleys were relaying their locations for the first couple hours of service and then both went down.  Today, we started off seeing both trolleys but now Trolley 1 is showing and Trolley 2 is not. 

I was wondering if you could take a look at the wifi activity and see if we're being throttled down by Cradlepoint? I'm having a difficult time diagnosing the problem since it seems fairly random. We had the same issues last weekend.

Anyway, please let me know.

Thanks,
Grant

**Comment by ajhodges** [comment]
Writer of the trolley app here - the app does not cache data if service is
unavailable. However it may be that our connections might not be
immediately timing out when there is a loss of connectivity. That would
explain the "superspeed" trolley behavior that we sometimes see when a
trolley comes back online, but it would not explain the loss of
connectivity. I have been planning on debugging/fixing the slow timeouts,
but when that is fixed we will have even more connectivity issues, because
that issue is probably actually masking a lot of smaller outages.

The app is functionally pretty simple, it requests location updates from
the Android API and then sends HTTP POST requests to our REST API. It does
not save any updates or anything. So (outside of the timeout issue or some
other bug we haven't noticed yet), if the trolley is not getting location
updates it's almost certainly due to a network connectivity issue
(slow/intermittent service) or a power issue. I'm willing to work with your
IT team to debug these issues!

**Comment by bikeoid** [comment]
I'm pretty sure that the equipment is powered down each day.   We had issues last weekend from Thursday through Sunday with both trolleys going up and down - sometimes going down in the middle of a run, then coming back.   So it will take more than a reboot to work around the problem.

**Comment by agautsc** [comment]
I'm with Mike ( @bikeoid ) Until we get trolleys staying connected for an entire weekend or two we shouldn't push it more marketing than we already have running. 

I could meet Wednesday at 9am if that works for others.

**Comment by bikeoid** [comment]
I'm good for a meeting on Wednesday at 9am.

**Comment by greenlinktransit** [comment]
Do you guys want to meet at Greenlink or a coffee shop?

**Comment by agautsc** [comment]
Let's do Methodical.

On Tue, Nov 3, 2015 at 8:53 AM, greenlinktransit <notifications@github.com>
wrote:

> Do you guys want to meet at Greenlink or a coffee shop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforgreenville/trolley-tracker-ios-client/issues/11#issuecomment-153361082>
> .
>



-- 
------------------------------
Adam Gautsch
OrangeCoat.com
800-890-1702 x0
http://www.orangecoat.com/people/adam

**Comment by agautsc** [comment]
Of course, the other thing we could do is meet on the other side of Main near the trolleys (say Spill the Beans). After we meet we could head over to the trolleys and work on the wi-fi settings a little bit.

**Comment by ajhodges** [comment]
I want in! Although if we are going to go tinker with the tablets
afterwards, I suggest somewhere a little closer like eggs up grill. Up to
yall!

**Comment by agautsc** [comment]
:egg: :+1: 9am. 

See y'all there.

**Comment by greenlinktransit** [comment]
Eggs Up at 9AM works for me.  I'll touch base with Maintenance to make sure someone can help us get the Trolleys started (it's harder than you think).

**Comment by greenlinktransit** [comment]
I talked to Steve and apparently one of our Trolleys just went to the body shop.  It should be back for Thursday's evening service.  If you guys want to look at both of them at the same time, let's try to reschedule for Thursday afternoon/early evening.  I'm out of town Friday - Sunday.  Otherwise, if you're okay looking at just one trolley, let's continue with the original plan.  Let me know what you prefer.

**Comment by bikeoid** [comment]
I'd prefer Wednesday at 9am to see what we can learn and come up with a more advanced troubleshooting plan for the weekend if necessary.

**Comment by agautsc** [comment]
How about we do this. Meet tomorrow as planned and go work with the tablet on the trolley that is there. That way we can have an A/B test of tablets to see if anything we did helped keep one up and running or not.

**Comment by greenlinktransit** [comment]
Works for me.

**Comment by greenlinktransit** [comment]
Do you guys still want us (Greenlink) to embed a Trolley Tracker map on our website?  Also, do you guys have a logo that we could post on our website?

**Comment by jeremywight** [comment]
Yeah that would be great! The sites have been updated. Here is a link to the icons: 
https://app.box.com/s/ntfu86u3sycw0fa9s1514m6tzvwh38xo
https://app.box.com/s/zwc1rvmrkriya1n1lzrb52tiotnj4fbq

**Comment by greenlinktransit** [comment]
I'm unable to access those links without paying.

**Comment by agautsc** [comment]
Give this link https://drive.google.com/drive/folders/0B1Wxj_5D6dLNQldIWnZ3c1RHbjQ a shot.

**Comment by greenlinktransit** [comment]
Got it -- thanks! What about the embedded trolley tracker map? Does someone have the HTML code for that?

**Comment by agautsc** [comment]
````    <iframe src="http://linktheorigi.webfactional.com/trolley/" class="shrink" width="100%" seamless></iframe>   ````

Give this a shot.

**Comment by greenlinktransit** [comment]
Adam -- the code worked, but the map is quite narrow (see screen shot attached).  Any way the dimensions can be enlarged?

![trolley tracker map - greenlink website](https://cloud.githubusercontent.com/assets/14838562/12205259/7f11569c-b607-11e5-916c-3b4f0d7912ab.jpg)

**Comment by agautsc** [comment]
You're going to need to add a height, unless @Linktheoriginal knows a better way. Next to the width="100%" try something like height="500px"

**Comment by jeremywight** [comment]
You could do a height of 450px. I have it set via CSS so that it is larger
on the desktop (600px) vs mobile (450px) so that people can still scroll
down on the mobile device.
