### ISSUE TITLE
New round of invites (12/2)

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-ios-client#15]
@austin9350 

I wrote a quick email I'm going to send to beta testers letting them know about the updates to the beacon. Can you send out invites to any iOS folks who haven't gotten invites yet? I don't want to send an email to folks who haven't gotten the beta invite yet.

Thank ya.
-Adam

**Comment by austin9350** [comment]
@agautsc Just sent them.
