### ISSUE TITLE
Trolley Tracker Public download link

### ISSUE THREAD

**Issue by austin9350** [codeforgreenville/trolley-tracker-ios-client#16]
https://itunes.apple.com/us/app/trolley-tracker-greenville/id1039575794?ls=1&mt=8

**Comment by agautsc** [comment]
I just sent out this link to a bunch of folks who signed up for beta testing over the last week or two.

**Comment by jeremywight** [comment]
That link is bad it should be:
https://itunes.apple.com/us/app/trolley-tracker-greenville/id1039575794?ls=1&mt=8

It was missing the "."s
