### ISSUE TITLE
Correct URL for server name

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-ios-client#25]
There is an old server name embedded in the app:

 URLs.swift , line 92

            return "http://tracker.wallinginfosystems.com/api"

 should be

            return "http://api.yeahthattrolley.com/api"

 It had worked until we switched to the new server this week.   @austin9350

**Comment by bikeoid** [comment]
Temporary patch in place to echo the production server trolley locations to the old server until a fix can be released.

**Comment by austin9350** [comment]
I’ll push a fix out asap, hopefully tomorrow.

**Comment by austin9350** [comment]
New build with the updated server URL has been submitted for TestFlight and AppStore review. Version 1.3.1 build 29.

**Comment by jeremywight** [comment]
Without tracking the actual Trolleys (since they aren't running) looks good
to me

**Comment by austin9350** [comment]
Update has been approved and is ready to release. Appears to be working as far as I see. Unless anyone sees a problem I’ll go ahead and release.

**Comment by austin9350** [comment]
Update has been released

**Comment by bikeoid** [comment]
Test flight arrived and confirmed that it is using the right server, and everything else looks good.
