### ISSUE TITLE
Upgrade to Swift 1.2

### ISSUE THREAD

**Issue by joelshaffer** [codeforgreenville/trolley-tracker-ios-client#4]
I have updated the project to build on Xcode 6.4 / Swift 1.2, would you like me to commit?

**Comment by jeremywight** [comment]
@austin9350 ^^^

**Comment by austin9350** [comment]
Hi @joelshaffer - sorry I just saw this. We updated the project during one of the hackathons, but the updates have been going to dev instead of master.
