### ISSUE TITLE
App Store Status

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-ios-client#5]
@austin9350 - Any update on the App Store submission process?

**Comment by jeremywight** [comment]
AUSTIN: 
Hey Jeremy, I got everything setup with the account and I just got a beta test version approved about an hour ago.
That will allow us to give 1,000 people access to preview/test it.
I’m with Adam on being a little concerned about doing a general rel
ease until the trolley data is more consistent.

The way Apple does it is a little different than Google. People give us email addresses and we put those in iTunes Connect and it sends them invitations.
I created trolleytrackergreenville@gmail.com for registering the Apple account.
If people that want to test send email there I'll see it and add them.
I could also set you up with access to the apple account to be able to add folks if you want.
And/or Adam.

ME:
It seems we could easily automate that process to be: I send email via web form to be a beta tester, auto response from us to watch their email for the invite, programmatically add them to the list and they get an "auto response" from Apple with the download link. Possible?

AUSTIN:
I think so. Here's an example of someone that did something like that, looks like it's somewhat tied to being on Heroku. https://github.com/fastlane/boarding

@agautsc @austin9350

**Comment by agautsc** [comment]
That boarding app seems pretty cool. Is there a wonder if there is something like that could work for both Android and iOS. It makes sense to me to have a single Beta Tester sign up form https://github.com/codeforgreenville/trolley-tracker/issues/79

If we can't automate that I'd be willing to manually enter info in and send out the welcome emails. I think it's worth giving folks an easy way to email us in case they are having trouble installing or using the app.

**Comment by agautsc** [comment]
What's the process for getting folks iOS beta accounts? A couple of people have signed up for the Beta program on iOS (twice as many have signed up for Android ;-)  ) and I'd like to send them welcome emails tomorrow morning. I assume that @austin9350 needs to add them to account somewhere and the welcome email needs to have some sort of link to the iTunes store or such.

**Comment by austin9350** [comment]
You're correct that they'll need to be added to the account. Adding them automatically sends them an invitation from iTunes with instructions on how to download it.

**Comment by agautsc** [comment]
Austin,

I shared the Google Spreadsheet of Beta signups. All the folks with dates by their name have received invites. That should be all the Android folks. If you can send out the invites to the iOS folks we should be good to go.

**Comment by austin9350** [comment]
I invited the folks from that group and updated the spreadsheets with the date.
Let me know if more sign up.

-- 
Austin Younts


On September 20, 2015 at 8:30:20 AM, Adam Gautsch (notifications@github.com) wrote:

Austin,

I shared the Google Spreadsheet of Beta signups. All the folks with dates by their name have received invites. That should be all the Android folks. If you can send out the invites to the iOS folks we should be good to go.

**Comment by agautsc** [comment]
Awesome. Thanks.

**Comment by agautsc** [comment]
@austin9350 

I just sent out an email to 138 folks who are part of the Upstate Transit Coalition and we're getting some more sign ups now. It would be good to send out a second round of invites tomorrow before 6pm when the trolley fires back up.

**Comment by austin9350** [comment]
I just invited the new ones that were added since yesterday. I'll try to check again tomorrow if I have time over lunch.
