### ISSUE TITLE
New round of invites

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-ios-client#7]
We've got a bunch of new iOS folks ready for invites for the weekend.

**Comment by agautsc** [comment]
@austin9350 Can you send out invites before this weekend? Fall for Greenville is this weekend and the trolley tracker app could get some good use.

**Comment by austin9350** [comment]
Just sent out another round.

**Comment by agautsc** [comment]
@austin9350 Can you send out another round of invites today? Fall for Greenville starts tonight and I'm going to send an email to everyone who's signed up so far letting them know they can use the TT for the weekend.

**Comment by agautsc** [comment]
@austin9350 We've got a bunch of iOS folks signed up and ready for invites.
